### ISSUE TITLE
Calling __init__ outside transform

### ISSUE THREAD

**Issue by cgarciae** [deepmind/dm-haiku#50] opened 2020-07-02 14:23 UTC
Hey,

I want to create a Haiku compatible library which provides a Keras-like interface called Elegy. I love how easy it is to use Haiku, however, I would like users to code something like this:

```python
module = hk.Sequential([
      hk.Flatten(),
      hk.Linear(300), jax.nn.relu,
      hk.Linear(100), jax.nn.relu,
      hk.Linear(10),
])

model = Model(
      module,
      loss=...,
      metrics=dict(
            accuracy=Accuracy(),  # this is probably an hk.Module as well
      ),
      optimizer=...,
)
```
Instead of checking if `__init__` is called inside `hk.transform` wouldn't it make more sense to check if `__call__` is called inside of this context? If this is not possible because you are not able to intercept `__call__` maybe having the user implement something like `call` or `apply` would be better?

**Comment by cgarciae** [comment] 2020-07-02 15:24
I've created a naive hack by commenting a couple of lines on `ModuleMetaclass`:

```python
    def __call__(cls: Type[T], *args, **kwargs) -> T:
        ...

        # Now attempt to initialize the object.
        init = with_name_scope("__init__", cls.__init__)
        # init(module, *args, **kwargs)

        module._auto_repr = utils.auto_repr(
            cls, *args, **kwargs
        )  # pylint: disable=protected-access

        # ran_super_ctor = hasattr(module, "module_name")
        # if not ran_super_ctor:
        #     raise ValueError(
        #         "Constructing an hk.Module without calling the super constructor "
        #         "is not supported. Add the following as the first line in your "
        #         "__init__ method:\n\nsuper(%s, self).__init__()" % cls.__name__
        #     )
```
And defining `__call__` like this on `Module`:

```python
def __call__(self, *args, **kwargs):
        self.__init__()
        return self.call(*args, **kwargs)
```

Created this test layer:

```python
class AddParam(Module):
    @hk.transparent
    def call(self, x):
        a = hk.get_parameter("a", [2, 3], init=hk.initializers.VarianceScaling())

        return a + x
```
And can successfully call it like this:

```python
module = AddParam()
net = hk.transform(module)
params = net.init(jax.random.PRNGKey(42), 1)
y = net.apply(params, 1)

print(net)
print(params)
print(y)
```
Can you comment on the possible pitfalls of these changes?

**Comment by trevorcai** [comment] 2020-07-03 01:19
This looks like a duplicate of #16. The main reason for `__init__` being called inside of `hk.transform` is that it allows us to fetch the module name at construction & expose it as an attribute of the module. These names are the backbone of how we route params/state to the right places!

This comment goes into a bit more detail:
https://github.com/deepmind/dm-haiku/issues/16#issuecomment-593139209

If I've de-duped this incorrectly, please re-open and let me know why!

**Closed by trevorcai** 2020-07-03 01:19 UTC
